### ISSUE TITLE
Video URL hardcoded?

### ISSUE THREAD

**Issue by toemat** [AlexMNet/sandals-latest-sermon#16]
Hi! I noticed the video url is maybe hardcoded instead of using the data from the network response?

https://github.com/AlexMNet/sandals-latest-sermon/blob/77dc5c4c199b1b0ab5a35a78bc97a12c107ab7a1/components/slug/Main.js#L20-L22

**Comment by AlexMNet** [comment]
@toemat oh geez! Must have left that when I was testing the HLS library. Great eye! Fixed and pushed!
