### ISSUE TITLE
URL slug hardening

### ISSUE THREAD

**Issue by toemat** [AlexMNet/sandals-latest-sermon#17]
Hi again! Great idea here!

Sometimes we have weird characters in the title that might not be so compatible as part of a url. I'd love to see this function fleshed out so that it only outputs lowercase a-z, 0-9, and hyphen.

Would be cool if it didn't output multiple hyphens in a row for something like "Learning - Part 1"

https://github.com/AlexMNet/sandals-latest-sermon/blob/77dc5c4c199b1b0ab5a35a78bc97a12c107ab7a1/functions/functions.js#L12-L14

**Comment by toemat** [comment]
New version looks good, nice work!

**Comment by AlexMNet** [comment]
@toemat thank you!
